name: Auto Merge Paired PRs
on:
  pull_request_target:
    types: [closed]   # fires when base PR is merged
jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract pair-id label
        id: labels
        run: |
          PAIR_ID=$(jq -r '.pull_request.labels[]?.name | select(startswith("pair-id:"))' <<< '${{ toJson(github.event) }}')
          echo "PAIR_ID=$PAIR_ID" >> $GITHUB_ENV

      - name: Find submodule PR
        run: |
          if [ -z "$PAIR_ID" ]; then
            echo "No pair-id label, nothing to do."
            exit 0
          fi
          PR=$(gh pr list --repo ant-man21/sub-github-actions --state open --json number,title,labels | jq -r ".[] | select(.labels[].name==\"$PAIR_ID\") | .number")
          if [ -z "$PR" ]; then
            echo "No matching submodule PR for $PAIR_ID"
            exit 0
          fi
          echo "Found submodule PR #$PR"
          echo "SUB_PR=$PR" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Squash merge submodule PR
        if: env.SUB_PR != ''
        run: |
          gh pr merge $SUB_PR --repo ant-man21/sub-github-actions --squash --admin --delete-branch --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
