name: Paired Integration
on:
  workflow_dispatch:
    inputs:
      SUBMODULE_PR:
        description: 'Submodule PR number'
        required: true
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Fetch submodule PR head
        run: |
          PR=${{ github.event.inputs.SUBMODULE_PR }}
          git -C submodule fetch origin pull/$PR/head:refs/pr/$PR
          git -C submodule checkout refs/pr/$PR
      - run: ./scripts/build.sh
