name: Validate Submodule SHA
on:
  pull_request:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Get submodule SHA
        id: sub
        run: |
          SUB_SHA=$(git ls-tree HEAD submodule | awk '{print $3}')
          echo "sha=$SUB_SHA" >> $GITHUB_OUTPUT
      - name: Check SHA on submodule/main (or paired PR)
        run: |
          SUB_SHA=${{ steps.sub.outputs.sha }}
          # Fetch main
          git -C submodule fetch origin main
          if git -C submodule merge-base --is-ancestor "$SUB_SHA" origin/main; then
            echo "✅ Submodule SHA is on submodule/main"
            exit 0
          fi

          # If not on main, check if paired PR exists
          echo "ℹ️ Submodule SHA not on main, checking for paired PR..."
          PR=$(gh pr list --repo ant-man21/sub-github-actions --state open --json number,headRefOid | jq -r ".[] | select(.headRefOid==\"$SUB_SHA\") | .number")
          if [ -n "$PR" ]; then
            echo "✅ Submodule SHA matches open PR #$PR"
            exit 0
          else
            echo "❌ Submodule SHA not on main or linked PR"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
